# Generated by Django 6.1 on 2026-08-16 23:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='genotype',
            field=models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('AC', 'AC')], max_length=5),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='marital_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='SINGLE', max_length=15),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='account_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='PartnerPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_age', models.PositiveIntegerField(default=18)),
                ('max_age', models.PositiveIntegerField(default=60)),
                ('preferred_genotype', models.CharField(blank=True, help_text='e.g., AA, AS acceptable', max_length=10)),
                ('preferred_state', models.CharField(blank=True, max_length=100)),
                ('preferred_marital_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='common.memberprofile')),
            ],
        ),
    ]
