# Generated by Django 6.1 on 2026-08-16 23:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_memberprofile_about_me_memberprofile_genotype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compatibility_score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SUGGESTED', 'Suggested'), ('LIKED', 'Liked'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='SUGGESTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('matched_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_with', to='common.memberprofile')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_initiated', to='common.memberprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'matched_profile')},
            },
        ),
    ]
